---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mikai233.
--- DateTime: 2022/12/23 11:42
---

local dir = "lua/managers"

for _, file in pairs(IOHelper.list_files(dir)) do
    local manager_name = string.gsub(string.sub(file, 1, #file - 4), "\\", "/")
    if manager_name ~= dir .. "/managers" then
        local manager = require(manager_name)
        if manager.init then
            manager:init()
        end
    end
end