---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mikai233.
--- DateTime: 2022/12/23 11:41
---

---@class PlayerManager
local PlayerManager = {

}

function PlayerManager:init()
    info("PlayerManager init done")
end

function PlayerManager:get_server_time()
    return self.server_timestamp
end

function PlayerManager:set_server_time(server_timestamp)
    self.server_timestamp = server_timestamp
end

function PlayerManager:set_ping_schedule_key(key)
    self.ping_schedule_key = key
end

function PlayerManager:get_ping_schedule_key()
    return self.ping_schedule_key
end

return PlayerManager