apiVersion: batch/v1
kind: Job
metadata:
  name: antares-runtime-config
  namespace: antares
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: antares-runtime-config
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init
          image: akka-game-server-tools:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: antares-runtime-env
