package com.mikai233.common.config.luban

import io.github.realmlabs.asteria.config.ConfigTable
import io.github.realmlabs.asteria.config.ConfigTableName
import kotlin.reflect.KClass

/**
 * Stable project-side base class for exposing Luban-generated tables through the `ConfigTable` abstraction.
 *
 * Concrete `TbXxx` adapters and the `GameTables` component are generated by `:common:refreshLubanConfig`.
 */
abstract class GameMapConfigTable<K : Any, R : Any>(
    name: String,
    override val keyType: KClass<K>,
    override val rowType: KClass<R>,
    rows: Map<K, R>,
) : ConfigTable<K, R> {
    override val name: ConfigTableName = ConfigTableName(name)
    private val rows: Map<K, R> = rows.toMap()

    override val size: Int get() = rows.size

    override val ids: Set<K> get() = rows.keys

    override fun get(id: K): R? {
        return rows[id]
    }

    override fun all(): Collection<R> {
        return rows.values
    }
}
