dependencies {
    implementation(platform(libs.spring.boot.dependencies))
    testImplementation(platform(libs.spring.boot.dependencies))
    testImplementation(platform(libs.test.junit.bom))
    testImplementation(libs.test.junit.jupiter)
    testImplementation(libs.spring.boot.starter.test)
    implementation(libs.bundles.asteria.foundation)
    implementation(libs.bundles.asteria.cluster)
    implementation(libs.bundles.asteria.script)
    implementation(libs.asteria.gm.spring.boot.starter)
    implementation(libs.asteria.gm.script.spring.boot.starter)
    implementation(libs.asteria.gm.patch.spring.boot.starter)
    implementation(libs.asteria.gm.config.spring.boot.starter)
    implementation(libs.asteria.gm.config.center.spring.boot.starter)
    implementation(libs.asteria.gm.cluster.spring.boot.starter)
    implementation(libs.asteria.gm.cluster.pekko)
    implementation(libs.asteria.script.job.mongodb.spring.boot.starter)
    implementation(libs.bundles.pekko.common)
    implementation(libs.kotlinx.core)
    implementation(libs.kotlinx.datetime)
    implementation(libs.kotlinx.reactor)
    implementation(libs.bundles.spring.boot.web)
    implementation(libs.jcommander)
    implementation(project(":common"))
    implementation(project(":proto"))
}

tasks.test {
    useJUnitPlatform()
}
