---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dream.
--- DateTime: 2023/2/6 16:49
---

local json = require("lua/ext/json")

local ConsoleHandler = {

}

function ConsoleHandler:init()
    EventDispatcher:add_listener(Rust2LuaEvent.ConsoleCommand(), self.on_gm_command, self)
    MessageDispatcher:add_listener("GmOrderResp", self.on_gm_order_resp, self)
    info("ConsoleHandler init done")
end

function ConsoleHandler:on_gm_command(params)
    local splitParams = Utils.splitn(params[1], 2, " ")
    local maybeRequest = splitParams[1]

    if string.sub(maybeRequest, 1, string.len("$")) == "$" then
        local request = string.sub(maybeRequest, 2)
        local requestData = load("return " .. splitParams[2])()
        send_message(request, requestData)
    else
        send_message("GmOrderReq", { param = params[1] or {} })
    end
end

function ConsoleHandler:on_gm_order_resp(resp)

end

return ConsoleHandler