---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mikai233.
--- DateTime: 2022/12/22 15:13
---

local dir = "lua/handlers"

for _, file in pairs(IOHelper.list_files(dir)) do
    local handler_name = string.gsub(string.sub(file, 1, #file - 4), "\\", "/")
    if handler_name ~= dir .. "/handlers" then
        local handler = require(handler_name)
        if handler.init then
            handler:init()
        end
    end
end