plugins {
    alias(libTool.plugins.ksp)
}

dependencies {
    testImplementation(platform(libTest.junit.bom))
    testImplementation(libTest.junit.jupiter)
    api("io.github.mikai233:foundation-core:1.0-SNAPSHOT")
    api("io.github.mikai233:foundation-actor:1.0-SNAPSHOT")
    api("io.github.mikai233:foundation-id:1.0-SNAPSHOT")
    api("io.github.mikai233:foundation-id-zookeeper:1.0-SNAPSHOT")
    api("io.github.mikai233:cluster-config:1.0-SNAPSHOT")
    api("io.github.mikai233:cluster-pekko:1.0-SNAPSHOT")
    api("io.github.mikai233:starter-game-server-pekko:1.0-SNAPSHOT")
    api("io.github.mikai233:persistence-core:1.0-SNAPSHOT")
    api("io.github.mikai233:persistence-mongodb:1.0-SNAPSHOT")
    api("io.github.mikai233:config-core:1.0-SNAPSHOT")
    api("io.github.mikai233:config-center-zookeeper:1.0-SNAPSHOT")
    api("io.github.mikai233:config-luban:1.0-SNAPSHOT")
    api("io.github.mikai233:config-publisher:1.0-SNAPSHOT")
    api("io.github.mikai233:script-core:1.0-SNAPSHOT")
    api("io.github.mikai233:script-pekko:1.0-SNAPSHOT")
    api("io.github.mikai233:script-engine-groovy:1.0-SNAPSHOT")
    api("io.github.mikai233:script-engine-jar:1.0-SNAPSHOT")
    implementation(libPekko.bundles.common)
    implementation(libKotlin.bundles.common)
    implementation(libKotlinx.core)
    runtimeOnly(libKotlinx.core.jvm)
    implementation(libKotlinx.datetime)
    implementation(libTool.bundles.curator)
    implementation(libLog.bundles.common)
    implementation(libTool.bundles.jackson)
    implementation(libTool.jackson.protobuf)
    testImplementation(libTool.reflections)
    implementation(libTool.protobuf.kotlin)
    implementation(libTool.protobuf.java.util)
    implementation(libTool.bcprov)
    implementation(libTool.groovy.all)
    implementation(libTool.guava)
    implementation(libTool.jcommander)
    implementation(libTool.spring.data.mongodb)
    implementation(libTool.spring.retry)
    implementation(libTool.mongodb.driver.sync)
    implementation(libTool.pekko.kryo)
    implementation(libTool.caffeine)
    implementation(libTool.kryo)
    implementation(libTool.lz4)
    implementation(libTool.netty)
    implementation(libTool.bundles.prometheus)
    implementation(project(":proto"))
    ksp(project(":processor"))
    ksp("io.github.mikai233:persistence-mongodb-ksp:1.0-SNAPSHOT")
}

tasks.test {
    useJUnitPlatform()
}
