pekko {
  loggers = ["org.apache.pekko.event.slf4j.Slf4jLogger"]
  logging-filter = "org.apache.pekko.event.slf4j.Slf4jLoggingFilter"
  loglevel = debug
  stdout-loglevel = info
  log-dead-letters = 100

  # Specifies the default loggers dispatcher
  loggers-dispatcher = "pekko.actor.logger-dispatcher"

  extensions = [
    "org.apache.pekko.cluster.pubsub.DistributedPubSub"
  ]

  actor {
    provider = cluster
    debug {
      autoreceive = off
      lifecycle = off
      log-sent-messages = off
      log-received-messages = off
    }

    logger-dispatcher {
      type = Dispatcher
      executor = "thread-pool-executor"
      thread-pool-executor {
        fixed-pool-size = 1
      }
      throughput = 100
    }

    serializers {
      kryo = "io.altoo.serialization.kryo.pekko.PekkoKryoSerializer"
    }

    serialization-bindings {
      "com.mikai233.common.message.Message" = kryo
    }

    deployment {
      /scriptActorRouter {
        router = broadcast-group
        routees.paths = ["/user/scriptActor"]
        cluster {
          enabled = on
          allow-local-routees = on
        }
      }

      /broadcastRouter {
        router = broadcast-group
        routees.paths = ["/user/broadcastActor"]
        cluster {
          enabled = on
          allow-local-routees = on
        }
      }
    }
  }

  cluster {
    sharding {
      passivation.default-idle-strategy.idle-entity.timeout = off
      handoff-timeout = 60s
    }
  }

}

pekko-kryo-serialization {
  kryo-initializer = "com.mikai233.common.serde.XKryoInitializer"
  implicit-registration-logging = true
  kryo-trace = false
}
