package com.mikai233.shared.excel

import kotlin.reflect.KClass

/**
 * Generated by GameConfigImplDepsGenerator
 * 所有[GameConfig]的实现类的依赖
 * 使用静态注册而不使用运行时反射的原因是为了加快启动速度
 */
public val ConfigDeps: Array<KClass<*>> = arrayOf(
    GameConfigManager::class,

    )
