---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mikai233.
--- DateTime: 2022/12/21 11:55
---
package.cpath = package.cpath .. ';embedded/?.dll'
local dbg = require('emmy_core')
dbg.tcpListen('localhost', 9955)