---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mikai233.
--- DateTime: 2022/12/23 19:05
---

-- for lua code usage only
LuaEvent = {
    Connected = "Connected",
    SharedKeyHaveSet = "SharedKeyHaveSet",
    LoginSuccess = "LoginSuccess",
}

-- for code insight
Lua2RustEvent = Lua2RustEvent

Rust2LuaEvent = Rust2LuaEvent