/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
    export interface GlobalComponents {
        AppShell: typeof import('./src/components/AppShell.vue')['default']
        ElButton: typeof import('element-plus/es')['ElButton']
        ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
        ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
        ElEmpty: typeof import('element-plus/es')['ElEmpty']
        ElForm: typeof import('element-plus/es')['ElForm']
        ElFormItem: typeof import('element-plus/es')['ElFormItem']
        ElIcon: typeof import('element-plus/es')['ElIcon']
        ElInput: typeof import('element-plus/es')['ElInput']
        ElMenu: typeof import('element-plus/es')['ElMenu']
        ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
        ElOption: typeof import('element-plus/es')['ElOption']
        ElSegmented: typeof import('element-plus/es')['ElSegmented']
        ElSelect: typeof import('element-plus/es')['ElSelect']
        ElSpace: typeof import('element-plus/es')['ElSpace']
        ElSwitch: typeof import('element-plus/es')['ElSwitch']
        ElTable: typeof import('element-plus/es')['ElTable']
        ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
        ElTag: typeof import('element-plus/es')['ElTag']
        ElText: typeof import('element-plus/es')['ElText']
        ElUpload: typeof import('element-plus/es')['ElUpload']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
    }

    export interface GlobalDirectives {
        vLoading: typeof import('element-plus/es')['ElLoadingDirective']
    }
}
